enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
excluded-patches = "'Copy video URL' 'Downloads' 'Seekbar' 'Swipe controls' 'Change header' 'Return YouTube Dislike' 'Announcements' 'Enable debugging'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#000000"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"
excluded-patches = "'Hide cast button' 'Enable debugging'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#000000"

[GooglePhotos]
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
